import { AsyncPipe, NgFor, NgIf } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { of } from 'rxjs';
import { DisplayImage } from './display-image';
import { LoaderImgComponent } from './loader-img.component';
import { Image } from './model/image';

const SERIES = [
  {
    name: 'American gods',
    id: 55,
    status: {
      readCount: 0,
      possessedCount: 3,
      totalCount: 3,
      status: 'FINISHED',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'American vampire',
    id: 24,
    status: {
      readCount: 5,
      possessedCount: 5,
      totalCount: 5,
      status: 'FINISHED',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Animal Man',
    id: 168,
    status: {
      readCount: 0,
      possessedCount: 0,
      totalCount: 2,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Aquaman rebirth',
    id: 11,
    status: {
      readCount: 5,
      possessedCount: 5,
      totalCount: 5,
      status: 'FINISHED',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'ARSENE LUPIN',
    id: 44,
    status: {
      readCount: 0,
      possessedCount: 2,
      totalCount: 0,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Grand Angle',
    bookType: { id: 1, name: 'BD' },
    cycles: [],
  },
  {
    name: "Assassin's creed",
    id: 75,
    status: {
      readCount: 5,
      possessedCount: 5,
      totalCount: 5,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'les Deux royaumes',
    bookType: { id: 1, name: 'BD' },
    cycles: [],
  },
  {
    name: 'Basketful of heads',
    id: 115,
    status: {
      readCount: 1,
      possessedCount: 1,
      totalCount: 1,
      status: 'FINISHED',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman',
    id: 7,
    status: {
      readCount: 9,
      possessedCount: 9,
      totalCount: 0,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman - The dark prince charming',
    id: 129,
    status: {
      readCount: 2,
      possessedCount: 2,
      totalCount: 0,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Dargaud Bénélux',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman : La nuit des monstres',
    id: 157,
    status: {
      readCount: 1,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman & Robin eternal',
    id: 126,
    status: {
      readCount: 2,
      possessedCount: 2,
      totalCount: 2,
      status: 'FINISHED',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman Année Un',
    id: 134,
    status: {
      readCount: 1,
      possessedCount: 1,
      totalCount: 1,
      status: 'FINISHED',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman Curse of the White Knight',
    id: 60,
    status: {
      readCount: 1,
      possessedCount: 1,
      totalCount: 1,
      status: 'FINISHED',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman death metal',
    id: 117,
    status: {
      readCount: 0,
      possessedCount: 2,
      totalCount: 2,
      status: 'FINISHED',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman detective comics',
    id: 122,
    status: {
      readCount: 2,
      possessedCount: 2,
      totalCount: 2,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman eternal',
    id: 125,
    status: {
      readCount: 4,
      possessedCount: 4,
      totalCount: 4,
      status: 'FINISHED',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman imposter',
    id: 136,
    status: {
      readCount: 1,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman Infinite',
    id: 96,
    status: {
      readCount: 0,
      possessedCount: 2,
      totalCount: 4,
      status: 'FINISHED',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman metal',
    id: 120,
    status: {
      readCount: 3,
      possessedCount: 0,
      totalCount: 3,
      status: 'FINISHED',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman rebirth',
    id: 114,
    status: {
      readCount: 12,
      possessedCount: 11,
      totalCount: 12,
      status: 'FINISHED',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman Shadow War',
    id: 172,
    status: {
      readCount: 0,
      possessedCount: 0,
      totalCount: 1,
      status: 'FINISHED',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman terminal',
    id: 113,
    status: {
      readCount: 1,
      possessedCount: 1,
      totalCount: 1,
      status: 'FINISHED',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman The Dark Knight Returns',
    id: 105,
    status: {
      readCount: 0,
      possessedCount: 0,
      totalCount: 1,
      status: 'FINISHED',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman the Dark Knight Returns : The golden Child',
    id: 111,
    status: {
      readCount: 0,
      possessedCount: 0,
      totalCount: 1,
      status: 'FINISHED',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman The Dark Knight Strikes Again',
    id: 110,
    status: {
      readCount: 0,
      possessedCount: 0,
      totalCount: 1,
      status: 'FINISHED',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman universe',
    id: 104,
    status: {
      readCount: 0,
      possessedCount: 1,
      totalCount: 1,
      status: 'FINISHED',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman White Knight',
    id: 61,
    status: {
      readCount: 1,
      possessedCount: 1,
      totalCount: 1,
      status: 'FINISHED',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman white knight Harley Quinn',
    id: 64,
    status: {
      readCount: 1,
      possessedCount: 1,
      totalCount: 1,
      status: 'FINISHED',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman-Dark Knight III',
    id: 108,
    status: {
      readCount: 0,
      possessedCount: 0,
      totalCount: 2,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman, créature de la nuit',
    id: 59,
    status: {
      readCount: 1,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman, Joker war',
    id: 99,
    status: {
      readCount: 3,
      possessedCount: 3,
      totalCount: 3,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman:',
    id: 177,
    status: {
      readCount: 0,
      possessedCount: 4,
      totalCount: 4,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman: Ego',
    id: 87,
    status: {
      readCount: 1,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Batman: One Dark Knight',
    id: 148,
    status: {
      readCount: 0,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Blacksad',
    id: 23,
    status: {
      readCount: 1,
      possessedCount: 2,
      totalCount: 2,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Dargaud',
    bookType: { id: 1, name: 'BD' },
    cycles: [],
  },
  {
    name: 'Catwoman - à Rome',
    id: 91,
    status: {
      readCount: 0,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Catwoman eternal',
    id: 127,
    status: {
      readCount: 2,
      possessedCount: 2,
      totalCount: 2,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Catwoman: Le dernier braquage',
    id: 86,
    status: {
      readCount: 0,
      possessedCount: 1,
      totalCount: 1,
      status: 'FINISHED',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Cixi de Troy',
    id: 32,
    status: {
      readCount: 3,
      possessedCount: 3,
      totalCount: 3,
      status: 'FINISHED',
    },
    oneShot: false,
    editor: 'Soleil',
    bookType: { id: 1, name: 'BD' },
    cycles: [],
  },
  {
    name: 'Dans la tête de Sherlock Holmes',
    id: 167,
    status: {
      readCount: 1,
      possessedCount: 2,
      totalCount: 2,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Ankama',
    bookType: { id: 1, name: 'BD' },
    cycles: [],
  },
  {
    name: 'Daredevil',
    id: 48,
    status: {
      readCount: 3,
      possessedCount: 4,
      totalCount: 4,
      status: 'FINISHED',
    },
    oneShot: false,
    editor: 'Panini comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Daredevil (2019)',
    id: 137,
    status: {
      readCount: 7,
      possessedCount: 7,
      totalCount: 7,
      status: 'FINISHED',
    },
    oneShot: false,
    editor: 'Panini comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Dark Knight The Last Crusade',
    id: 112,
    status: {
      readCount: 0,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'DC infinite frontier',
    id: 97,
    status: {
      readCount: 0,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'DC Univers rebirth - Le Badge',
    id: 46,
    status: {
      readCount: 0,
      possessedCount: 0,
      totalCount: 0,
      status: 'UNKNOWN',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'DC Univers rebirth : Le Badge',
    id: 107,
    status: {
      readCount: 0,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Deathstroke',
    id: 14,
    status: {
      readCount: 5,
      possessedCount: 5,
      totalCount: 5,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Decorum',
    id: 41,
    status: {
      readCount: 1,
      possessedCount: 2,
      totalCount: 2,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: "Devil's Reign",
    id: 147,
    status: {
      readCount: 2,
      possessedCount: 3,
      totalCount: 3,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Panini comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Earth 2',
    id: 116,
    status: {
      readCount: 6,
      possessedCount: 6,
      totalCount: 6,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'East of West',
    id: 175,
    status: {
      readCount: 0,
      possessedCount: 0,
      totalCount: 3,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: "Ed Gein: Autopsie d'un Tueur en série",
    id: 161,
    status: {
      readCount: 0,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: true,
    editor: 'Delcourt',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Fables',
    id: 71,
    status: {
      readCount: 16,
      possessedCount: 23,
      totalCount: 23,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Future state Batman',
    id: 98,
    status: {
      readCount: 0,
      possessedCount: 2,
      totalCount: 2,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Future state Justice League',
    id: 101,
    status: {
      readCount: 0,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Future state Superman',
    id: 100,
    status: {
      readCount: 0,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Futures end',
    id: 123,
    status: {
      readCount: 4,
      possessedCount: 4,
      totalCount: 4,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Garth Ennis présente Hellblazer',
    id: 179,
    status: {
      readCount: 0,
      possessedCount: 0,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Grayson',
    id: 8,
    status: {
      readCount: 3,
      possessedCount: 3,
      totalCount: 3,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Green Arrow rebirth',
    id: 15,
    status: {
      readCount: 2,
      possessedCount: 3,
      totalCount: 3,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Harleen',
    id: 65,
    status: {
      readCount: 1,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Harley Quinn',
    id: 9,
    status: {
      readCount: 2,
      possessedCount: 4,
      totalCount: 4,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Harley Quinn Black + White + Red',
    id: 66,
    status: {
      readCount: 0,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Hit-Girl',
    id: 82,
    status: {
      readCount: 1,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Panini comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'House of M',
    id: 146,
    status: {
      readCount: 0,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: true,
    editor: 'Panini comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'House of Slaughter',
    id: 149,
    status: {
      readCount: 1,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban indies',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Il faut flinguer Ramirez',
    id: 26,
    status: {
      readCount: 2,
      possessedCount: 2,
      totalCount: 2,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Glénat',
    bookType: { id: 1, name: 'BD' },
    cycles: [],
  },
  {
    name: 'Immortal Hulk',
    id: 49,
    status: {
      readCount: 7,
      possessedCount: 8,
      totalCount: 10,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Panini comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Infinite crisis',
    id: 103,
    status: {
      readCount: 5,
      possessedCount: 5,
      totalCount: 5,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Injection',
    id: 43,
    status: {
      readCount: 3,
      possessedCount: 3,
      totalCount: 3,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Jessica Jones - Alias',
    id: 176,
    status: {
      readCount: 0,
      possessedCount: 1,
      totalCount: 2,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Panini comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Joker',
    id: 62,
    status: {
      readCount: 0,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Joker Infinite',
    id: 130,
    status: {
      readCount: 0,
      possessedCount: 3,
      totalCount: 3,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: "Jupiter's Circle",
    id: 154,
    status: {
      readCount: 1,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: true,
    editor: 'Panini comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: "Jupiter's legacy",
    id: 38,
    status: {
      readCount: 2,
      possessedCount: 3,
      totalCount: 3,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Panini comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Justice League',
    id: 102,
    status: {
      readCount: 6,
      possessedCount: 6,
      totalCount: 6,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Justice league, no justice',
    id: 118,
    status: {
      readCount: 1,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Justice Society of America',
    id: 93,
    status: {
      readCount: 0,
      possessedCount: 1,
      totalCount: 2,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Kaamelott',
    id: 76,
    status: {
      readCount: 7,
      possessedCount: 9,
      totalCount: 9,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Casterman',
    bookType: { id: 1, name: 'BD' },
    cycles: [],
  },
  {
    name: 'Kick-ass',
    id: 83,
    status: {
      readCount: 2,
      possessedCount: 2,
      totalCount: 2,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Panini comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Kick-Ass 2',
    id: 84,
    status: {
      readCount: 2,
      possessedCount: 2,
      totalCount: 2,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Panini comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Kick-Ass 3',
    id: 81,
    status: {
      readCount: 2,
      possessedCount: 2,
      totalCount: 2,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Panini comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Kickass: The new girl',
    id: 79,
    status: {
      readCount: 4,
      possessedCount: 4,
      totalCount: 4,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Panini France',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Killing joke',
    id: 109,
    status: {
      readCount: 0,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Kingdom Come',
    id: 174,
    status: {
      readCount: 0,
      possessedCount: 0,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Kingsman',
    id: 47,
    status: {
      readCount: 2,
      possessedCount: 2,
      totalCount: 2,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Panini comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: "La Quête de l'oiseau du temps",
    id: 74,
    status: {
      readCount: 0,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Dargaud',
    bookType: { id: 1, name: 'BD' },
    cycles: [],
  },
  {
    name: 'Lanfeust de Troy',
    id: 155,
    status: {
      readCount: 6,
      possessedCount: 6,
      totalCount: 6,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Soleil',
    bookType: { id: 1, name: 'BD' },
    cycles: [],
  },
  {
    name: 'Lanfeust des étoiles',
    id: 33,
    status: {
      readCount: 8,
      possessedCount: 8,
      totalCount: 8,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Soleil',
    bookType: { id: 1, name: 'BD' },
    cycles: [],
  },
  {
    name: 'Lanfeust odyssey',
    id: 31,
    status: {
      readCount: 10,
      possessedCount: 10,
      totalCount: 10,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Soleil',
    bookType: { id: 1, name: 'BD' },
    cycles: [],
  },
  {
    name: 'Le Batman qui rit',
    id: 121,
    status: {
      readCount: 1,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Le batman qui rit - Les infectés',
    id: 119,
    status: {
      readCount: 1,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: true,
    editor: 'Urban comics',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Le combat ordinaire',
    id: 178,
    status: {
      readCount: 0,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Dargaud',
    bookType: { id: 1, name: 'BD' },
    cycles: [],
  },
  {
    name: 'Le dernier des dieux',
    id: 25,
    status: {
      readCount: 1,
      possessedCount: 2,
      totalCount: 2,
      status: 'ON_GOING',
    },
    oneShot: false,
    editor: 'Urban',
    bookType: { id: 3, name: 'Comics' },
    cycles: [],
  },
  {
    name: 'Le donjon de Naheulbeuk',
    id: 77,
    status: {
      readCount: 10,
      possessedCount: 0,
      totalCount: 15,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Clair de lune',
    bookType: { id: 1, name: 'BD' },
    cycles: [],
  },
  {
    name: 'Le sorceleur',
    id: 85,
    status: {
      readCount: 8,
      possessedCount: 8,
      totalCount: 8,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Bragelonne',
    bookType: { id: 4, name: 'Roman' },
    cycles: [],
  },
  {
    name: 'Légendes de Troy - Nuit Safran',
    id: 30,
    status: {
      readCount: 1,
      possessedCount: 1,
      totalCount: 1,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Soleil',
    bookType: { id: 1, name: 'BD' },
    cycles: [],
  },
  {
    name: 'Les 5 terres',
    id: 4,
    status: {
      readCount: 9,
      possessedCount: 9,
      totalCount: 9,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Delcourt',
    bookType: { id: 1, name: 'BD' },
    cycles: [
      { id: 1, name: 'Angleon' },
      { id: 2, name: 'Lys' },
    ],
  },
  {
    name: 'Les arcanes de Naheulbeuk',
    id: 78,
    status: {
      readCount: 3,
      possessedCount: 3,
      totalCount: 3,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Clair de lune',
    bookType: { id: 1, name: 'BD' },
    cycles: [],
  },
  {
    name: 'Les conquérants de Troy',
    id: 29,
    status: {
      readCount: 4,
      possessedCount: 4,
      totalCount: 4,
      status: 'UNKNOWN',
    },
    oneShot: false,
    editor: 'Soleil',
    bookType: { id: 1, name: 'BD' },
    cycles: [],
  },
];

@Component({
  selector: 'app-series-list',
  standalone: true,
  imports: [LoaderImgComponent, NgFor, NgIf, AsyncPipe],
  template: `
    <h1>Series</h1>

    <ng-container *ngIf="(list$ | async) as seriesList">
      <ul class="series-list">
        <li *ngFor="let series of seriesList">
          <div class="left">
            <div class="zone-vignette">
              <app-loader-img [img]="img">
              </app-loader-img>
            </div>
          </div>

          <div class="zone-details">
            <h2 class="zone-titre">{{ series.name }}</h2>
            <span class="series-editor">{{ series.editor }} books</span>
          </div>
        </li>
      </ul>
    </ng-container>
  `,
  styleUrls: ['series-list.component.scss'],
})
export class SeriesListComponent extends DisplayImage {
  list$ = of(SERIES);
  img: Image | null = {
    src: 'https://bdi.dlpdomain.com/album/9791026828457/couv/M385x862/red-hood-souriez.jpg',
    alt: '',
  };

  constructor() {
    super('/files/covers');
  }
}
